### ISSUE TITLE
"left" attribute needs to be recalculated if the viewport's width changes

### ISSUE THREAD

**Issue by PAStheLoD** [makseo/ng2-sticky#12]
Hello,

First of all thank you for this nice component!

So, it looks like that resizing the browser (let's say the user rotates their mobile to landscape, or uses an old school desktop computer, or otherwise the window.innerWidth changes) results in an incorrect "left" attribute.

Are there plans to handle this problem?

**Comment by MehdiSaeedifar** [comment]
any progress?

**Comment by ImTheC** [comment]
The fix has been submitted here: https://github.com/makseo/ng2-sticky/pull/20

Just waiting for it to be merged.

In the meantime, if you can, you could manually edit the code based on the pull request.

**Comment by FriOne** [comment]
@makseo Guess this was not published to npm.

**Comment by makseo** [comment]
@FriOne, try to use the latest version (4.0.1)
PR from @ImTheC has to be in this release version.
