### ISSUE TITLE
Dynamic changing scrollFinish variable

### ISSUE THREAD

**Issue by rash2x** [makseo/ng2-sticky#13]
Hi! 

If our page can adding elements which change height of window, scrollFinish still have first defined value.

For example. Body height is 1000px. Then we add new element with 1000px height and now body height is 2000px. But scrollFinish is 1000px anyway. 

Maybe you will use getter, won't you?

```
private get scrollFinish():number {
        if (this.parentMode) {
            return this.containerStart - this.start - this.offsetBottom + (this.containerHeight - this.elemHeight);
        }

        return document.body.offsetHeight;
    }
```

**Comment by arkhamvm** [comment]
+1

**Comment by makseo** [comment]
It's a nice idea to use "getter", but unfortunately this solution will not work, because "scrollFinish" requires another parameters to be properly recalculated.

Here should be used "defineDimensions".

I will think about how to detect if the DOM was changed and run "defineDimensions".
