### ISSUE TITLE
Error encountered resolving symbol values statically

### ISSUE THREAD

**Issue by gkaran** [makseo/ng2-sticky#14]
I have an angular-cli project and tried to use the latest version of this project but I get the following error during compilation:

> ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in .../node_modules/ng2-sticky-kit/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in .../node_modules/ng2-sticky-kit/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in .../node_modules/ng2-sticky-kit/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in .../node_modules/ng2-sticky-kit/node_modules/@angular/core/index.d.ts, resolving symbol StickyModule in .../node_modules/ng2-sticky-kit/ng2-sticky-kit.ts, resolving symbol StickyModule in .../node_modules/ng2-sticky-kit/ng2-sticky-kit.ts

Where `...` is the absolute path to my project's root.

**Comment by makseo** [comment]
Please try to test with the latest versions of ng2-sticky & angular-cli.
