### ISSUE TITLE
Property 'element' is declared but never used

### ISSUE THREAD

**Issue by pcwa-ahendricks** [makseo/ng2-sticky#19]
Getting an error with Angular CLI when using the:
`"noUnusedLocals": true`
tsconfig.json option.  Setting the option to false is a workaround but I'm wondering if there is a better workaround. 

ERROR in .../node_modules/ng2-sticky-kit/src/ng2-sticky/ng2-sticky.ts (37,25): Property 'element' is declared but never used.
webpack: Failed to compile.

**Comment by makseo** [comment]
was fixed in v4.0.1
thanks
