### ISSUE TITLE
Please add a @Pipe/@Directive/@Component annotation

### ISSUE THREAD

**Issue by bflopez** [makseo/ng2-sticky#23]
I am looking to add ng2-sticky to my website but I keep getting a build error.

This is the errors I received when building:

```
ERROR in Unexpected module 'StickyModule in /home/dev/hunter/site/src/node_modules/ng2-sticky-kit/ng2-sticky-kit.ts' declared by the module 'AppModule in /home/dev/hunter/site/src/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './../$$_gendir/src/app/app.module.ngfactory' in '/home/dev/hunter/site/src/src'
 @ ./src/main.ts 4:0-81
 @ multi ./src/main.ts
```

I added import { StickyModule } from 'ng2-sticky-kit/ng2-sticky-kit'; to app.module.ts and added it to the declarations and then am using it in another component.

**Comment by makseo** [comment]
Section "declarations" is the wrong place.
You need to use the "imports".
