### ISSUE TITLE
Style Encapsulation // Directive

### ISSUE THREAD

**Issue by CanKattwinkel** [makseo/ng2-sticky#31]
Please disable Encapsulation by default. Otherwise styles provided by the application will get removed. 

Another (better) approach would be to use a directive or?

```

@Component({
    selector: 'sticky',
    template: '<ng-content></ng-content>',
    encapsulation: ViewEncapsulation.None
})
export class StickyComponent implements OnInit, AfterViewInit {
[...]
```

**Comment by makseo** [comment]
@CanKattwinkel , in this case a directive would be of course the better solution.
Also I'm not sure, that _ViewEncapsulation.None_ will not lead to other problems with styling.
Can you send please also an example, where you have a problem with styles?
Thanks!
