### ISSUE TITLE
Angular Package Format 

### ISSUE THREAD

**Issue by CanKattwinkel** [makseo/ng2-sticky#32]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```

### Repro steps.
using angular-cli

1. `ng new some-project`
2. `yarn add ng2-sticky-kit`
3. Add  `StickyModule` to `src/app/app.module.ts`
4. use IDE (IntelliJ's) import shortcut 

### Desired functionality.
I'd expect to use my autocomplete feature in order to import the projects module. But I'm forced to use a manually created import line ( `import {StickyModule} from 'ng2-sticky-kit/ng2-sticky-kit';`). 

The required module export is missing. To preserve the struggle I'd recommend you to take a look at https://github.com/filipesilva/angular-quickstart-lib 

It provides a decent build, supporting all required module systems. 

More information can be found [here](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit#).

**Comment by makseo** [comment]
Hi, @CanKattwinkel 
Thank you for your great advice.
From version v5.0.0 you can use autocomplete import in your IDE :)
