### ISSUE TITLE
Migrate to NG2 RC6

### ISSUE THREAD

**Issue by tenninebt** [makseo/ng2-sticky#4]
Components has to be declared in a module, something like :

@NgModule({
    declarations: [Sticky],
    imports:      [NgModule, Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, AfterViewInit]
})
export class StickyModule {}

hope it helps

**Comment by makseo** [comment]
@tenninebt , thank you! you can install version 1.0.7 for RC6. Now ngSticky is a component.

**Comment by tenninebt** [comment]
Well done, thanks! I'll test asap !

**Comment by tenninebt** [comment]
Not sure about the fix, actually you are exporting the module in the demo app (./demo/app.module.ts), that should be done in your ng2-sticky-kit.ts. Should look like this : 
```
import {NgModule} from '@angular/core';
import {Sticky} from '../src/ng2-sticky/ng2-sticky';

@NgModule({
    imports: [//All the imports needed by the elements of the module, so the ones need by the directive
       NgModule, Directive, ElementRef, Input, Output, EventEmitter, OnInit, OnDestroy, AfterViewInit],
    declarations: [
        Sticky
    ]
})
export class StickyModule {}
```

You should declare a StickyModule which will should have in its declarations the component/directive. Not sure if you really have to replace the directive by a component. Here is an extract from angular docs :  
> "Angular modules consolidate components, directives and pipes into cohesive blocks of functionality, each focused on a feature area, application business domain, workflow, or common collection of utilities."

Hope it is clear. If I have time, I'll try to do it and send a pull request, but honestly, unlikely as too busy these days.
