### ISSUE TITLE
Sticky directive

### ISSUE THREAD

**Issue by mkoczorowski** [makseo/ng2-sticky#40]
Docs show a sticky directive which does not exist here ? I htink directive would be better as wrapping <sticky> changes html context for example if I would like to make a table header sticky

**Comment by crutchcorn** [comment]
Try using this:
`import {StickyComponent} from 'ng2-sticky-kit';`

The module listed in the README does not export the component, so it naturally shouldn't work. Additionally, I've noticed that `<div sticky>` does not work as it is not defined in the component code. Instead, use `<sticky><div>`

**Comment by makseo** [comment]
@mkoczorowski try please to install v5.1.0
