### ISSUE TITLE
sticky does'n work

### ISSUE THREAD

**Issue by rniederer** [makseo/ng2-sticky#42]
Hello

I tried to use sticky for my sidebar. I use bootstrap 4 (beta 2). I did a row with two columns and want sticky the right column. but it doesn't work. 

Nice to know: The row with the columns is in a absolute div (id=content).

```
<div id="content">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="card" style="height: 1000px"></div>
            </div>
            <div class="col-md-3">
                <div sticky class="card">
                    <div class="card-body">
                        <router-outlet></router-outlet>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```

What did I wrong?

**Comment by davidericardo** [comment]
I'm facing the same issue. I can't use the module at all. 
It's imported in my main.module and then tried to use it in one of my components, with no luck so far. :S

**Comment by crutchcorn** [comment]
Try using this:
`import {StickyComponent} from 'ng2-sticky-kit';`

The module listed in the README does not export the component, so it naturally shouldn't work. Additionally, I've noticed that `<div sticky>` does not work as it is not defined in the component code. Instead, use `<sticky><div>`

**Comment by makseo** [comment]
hi @rniederer, at the moment you can use sticky only as a component, like this
<div><sticky></sticky></div>

@crutchcorn 
export should work
https://github.com/makseo/ng2-sticky/blob/master/src/lib/src/module.ts#L7
