### ISSUE TITLE
Sticky doesn't recalculate on screen resize

### ISSUE THREAD

**Issue by pajohns** [makseo/ng2-sticky#44]
When resizing a screen that has a sticky component that has converted the dom element to a static position with a left position, the left position doesn't update on screen resize. This causes unexpected results when the screen is resized whereby the element will appear over other objects on the page.

**Comment by TheSchmoe** [comment]
Having the same issue, deal breaker for me.

**Comment by TiboQc** [comment]
Having the same issue, went to production with that, but really is a big issue.

**Comment by thebarada** [comment]
+1

**Comment by chaabenMohamed** [comment]
I have the same issue, and I fixed it in fork just with those change, if you can  fix it in master.
![fix-reseize](https://user-images.githubusercontent.com/26092153/50395311-6f2eb700-0763-11e9-89cd-43fad66dba2c.png)
