### ISSUE TITLE
position value ignore

### ISSUE THREAD

**Issue by pcwa-ahendricks** [makseo/ng2-sticky#8]
I'm having an issue where unstick get's called prematurely as I scroll half way down the screen.  It seems the source of my issue is related to the value that get's loaded into the private `position` property, which will exceed the `scrollFinish` property causing unstick to trigger.  

Is there a suitable workaround for completely ignoring the position property? Maybe an input option for the component that allows the sticky to stick anywhere/indefinitely as you scroll down, and only unstick when resurfacing back to the top?

**Comment by makseo** [comment]
Unfortunately with the current version of the library, I do not see a quick solution to this problem. sorry :(
