### ISSUE TITLE
sticky-offset-bottom not working 

### ISSUE THREAD

**Issue by rsach** [makseo/ng2-sticky#9]
i am trying to use your lib the sticky-offset-top is working fine but the bottom one isn't working at all 

this is the link i'm using 

https://rsach.github.io/Project-1/

This is the snippet with the problem 

<div class=" col-sm-3 col-xs-3 col-md-3">
  <sticky  [sticky-parent]="false"  [sticky-offset-top]="60" sticky-offset-bottom="50"  [sticky-media-query]="'min-width: 500px'"  >
  <div class="navCaps" >
    <ul class="nav nav-pills nav-stacked " >
        <li class="active"><a href="#section1">Section 1</a></li>
        <li><a href="#section2">Section 2</a></li>
        <li><a href="#section3">Section 3</a></li>
      </ul>

   </div>   
    
  </sticky>
  </div>

**Comment by rsach** [comment]
`<div class=" col-sm-3 col-xs-3 col-md-3">
  <sticky  [sticky-parent]="false"  [sticky-offset-top]="60" sticky-offset-bottom="50"  [sticky-media-query]="'min-width: 500px'"  >
  <div class="navCaps" >
    <ul class="nav nav-pills nav-stacked " >
        <li class="active"><a href="#section1">Section 1</a></li>
        <li><a href="#section2">Section 2</a></li>
        <li><a href="#section3">Section 3</a></li>
      </ul>

   </div>   
    
  </sticky>
  </div>`

**Comment by rsach** [comment]
```
`<div class=" col-sm-3 col-xs-3 col-md-3">
  <sticky  [sticky-parent]="false"  [sticky-offset-top]="60" sticky-offset-bottom="50"  [sticky-media-query]="'min-width: 500px'"  >
  <div class="navCaps" >
    <ul class="nav nav-pills nav-stacked " >
        <li class="active"><a href="#section1">Section 1</a></li>
        <li><a href="#section2">Section 2</a></li>
        <li><a href="#section3">Section 3</a></li>
      </ul>

   </div>   
    
  </sticky>
  `</div>``
```

**Comment by makseo** [comment]
sorry, as seems to be, that your example doesn't work any more.
but you can look into the demo -> https://github.com/makseo/ng2-sticky/tree/master/demo.
block with "heading 1" uses "sticky-offset-bottom" and it works correct.
